### ISSUE TITLE
Please add support for std::basic_string_view

### ISSUE THREAD

**Issue by hia3** [boostorg/nowide#33]
It would be nice to have overloads of `widen`/`narrow` for `(w/u16/u32)string_view`, if possible.

**Comment by Frkymhn** [comment]
i want to work on this issues.please guide me

**Comment by Flamefire** [comment]
I'm going to clean up the header a bit and move the `basic_convert` function into detail, see https://github.com/boostorg/nowide/pull/61. Then it should be pretty easy: Instead of a (w)string take a (w)string_view and pass it on, just as the string function do. Obviously you'll need a check if string_view is supported. Look for a appropriate boost macro.

**Comment by Flamefire** [comment]
as for (u16/u32)string_view: You can take a template in widen and enable_if on the char type. I guess a trait `is_wide_char`  specialized for w/u16/u32 char would be appropriate

**Comment by Flamefire** [comment]
@hia3 I added a PR (#117) which makes those functions (and the `convert_string` template) accept string_view instances.

Let me know if that solves your problem
