### ISSUE TITLE
Make it a header-only library on non-Windows platforms.

### ISSUE THREAD

**Issue by Berrysoft** [boostorg/nowide#99]
I just cannot see why it is *not* header-only on *nix platforms.

**Comment by Flamefire** [comment]
Because it wouldn't work with `--std=c++xx` option as there are non-standard functions used, especially the environment modifying ones.   
Besides that it requires a compiled library on Windows, so for the sake of cross-platform development it is more reasonable to always have a compiled library instead of introducing additional conditionals in the build systems of the users

**Comment by Berrysoft** [comment]
OK, it seems fair...
